### PR TITLE
Add some details about ngrok

### PR DESCRIPTION
**Pull request by Explosion-Scratch**
- Perhaps add a custom User-Agent to the webui so that you don't have to click "Visit Site"?

### CODE REVIEW

**Comment by carefree0910** [comment]
I registered a new account and found out that even without clicking the `Visit Site`, I can still use the server 🤔

Did you go into trouble when you hadn't clicked that?

**Comment by carefree0910** [comment]
Strange, I asked some friends to test it out and one (and only one) of them cannot visit the `ngrok` until he clicked the `Visit Site`... I'll merge this PR then 😉

**Comment by Explosion-Scratch** [comment]
> Strange, I asked some friends to test it out and one (and only one) of them cannot visit the `ngrok` until he clicked the `Visit Site`... I'll merge this PR then 😉

Adding a custom User-Agent header in the webui when fetching would solve this. Just do:
```js
fetch("url", {
   headers: {
      "User-Agent": "NoliCreator/e29b484"
   }
})
```

**Comment by carefree0910** [comment]
Just curious, is the `e29b484` in this piece of code:

```typescript
fetch("url", {
   headers: {
      "User-Agent": "NoliCreator/e29b484"
   }
})
```

a random string, or something important? 😏

**Comment by Explosion-Scratch** [comment]
> Just curious, is the `e29b484` in this piece of code:
> 
> ```ts
> fetch("url", {
>    headers: {
>       "User-Agent": "NoliCreator/e29b484"
>    }
> })
> ```
> 
> a random string, or something important? 😏

Commit hash 😉 It would also be best practice to put ` (youremail@selfhostedemailisbetter.com)` after that

**Comment by carefree0910** [comment]
Got it! I'll dive into it a little bit later and try to integrate it in the webui codes! 😆

**Pull request merged**
